import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { turnFixture } from "../src/dev/turn-fixture.js";
import { GameSession } from "../src/app/game-session.js";
import { FileCampaignRepository } from "../src/persistence/campaign-repository.js";
import { PortraitAssetStore } from "../src/app/portrait-store.js";
import { createPlaytestServer } from "../src/ui/server.js";
import { CampaignState } from "../src/campaign/campaign-state.js";
import type { CampaignCommand } from "../src/campaign/types.js";

const PNG = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==", "base64");
test("Inventory UI HTTP: possession, states, safe sprite access and save roundtrip; zero generation", async t => {
  const { world, campaign } = turnFixture();
  const root = await mkdtemp(join(tmpdir(), "caldrevan-inventory-ui-")); t.after(() => rm(root, { recursive: true, force: true }));
  const store = new PortraitAssetStore(root, { layout: "campaign" }), repo = new FileCampaignRepository(world, root);
  const apply = (...commands: CampaignCommand[]) => campaign.apply({ expected_revision: campaign.revision, commands });
  const create = (name: string, position: Extract<CampaignCommand, { kind: "create_item" }>["position"], owner_id = "nicco") => ({ kind: "create_item" as const, name, description: `Description of ${name}.`, visual_description: "INTERNAL_VISUAL_SENTINEL", position, owner_id });
  apply(create("Borrowed knife", { kind: "carried", character_id: "nicco" }, "brenna"), create("Stored sword", { kind: "stored", location_id: "test_room" }), create("NPC lantern", { kind: "carried", character_id: "maren" }), create("Pending ring", { kind: "carried", character_id: "nicco" }), create("Failed letter", { kind: "carried", character_id: "nicco" }));
  apply({ kind: "place_item", item_id: "boots", position: { kind: "equipped", character_id: "nicco", slot: "feet", mode: "worn" } });
  const id = (name: string) => campaign.exportSnapshot().items.find(i => i.name === name)!.id;
  apply({ kind: "set_item_sprite", item_id: id("Borrowed knife"), sprite: { status: "pending" } }, { kind: "set_item_sprite", item_id: id("Pending ring"), sprite: { status: "pending" } }, { kind: "set_item_sprite", item_id: id("Failed letter"), sprite: { status: "pending" } });
  const file = "portrait_inventory_test.png", staged = await store.stage("turn_fixture", id("Borrowed knife"), PNG); await store.finalize(staged, "turn_fixture", id("Borrowed knife"), file);
  apply({ kind: "set_item_sprite", item_id: id("Borrowed knife"), sprite: { status: "ready", asset_ref: file, generated_from_visual_description: "INTERNAL_VISUAL_SENTINEL" } }, { kind: "set_item_sprite", item_id: id("Failed letter"), sprite: { status: "failed", error_code: "SECRET_ERROR_SENTINEL" } });
  let calls = 0;
  const session = GameSession.fromCampaign({ world, repository: repo, portrait_store: store, portrait_generator: { identity: { provider: "test", model: "test" }, async generate() { calls++; throw new Error("must not call"); } }, createCoordinator: () => ({ async *runTurn() {} }) }, campaign);
  const server = createPlaytestServer(session); server.listen(0, "127.0.0.1"); await once(server, "listening"); t.after(() => new Promise<void>(resolve => { server.closeAllConnections(); server.close(() => resolve()); }));
  const address = server.address(); if (!address || typeof address === "string") throw new Error("missing port"); const base = `http://127.0.0.1:${address.port}`;
  const response = await fetch(`${base}/api/inventory`), body = await response.text(), data = JSON.parse(body);
  assert.equal(response.status, 200); assert.doesNotMatch(body, /INTERNAL_VISUAL|SECRET_ERROR|asset_ref|portrait_inventory|owner_id/);
  assert.ok(data.items.some((i: any) => i.name === "Borrowed knife"), "ownership is not possession");
  assert.ok(!data.items.some((i: any) => ["Stored sword", "NPC lantern"].includes(i.name)));
  assert.ok(data.items.some((i: any) => i.position.kind === "equipped")); assert.ok(data.items.some((i: any) => i.sprite_status === "none"));
  assert.equal(data.items.find((i: any) => i.name === "Pending ring").sprite_status, "pending"); assert.equal(data.items.find((i: any) => i.name === "Failed letter").sprite_status, "failed");
  const knife = data.items.find((i: any) => i.name === "Borrowed knife");
  const image = await fetch(base + knife.sprite_url); assert.equal(image.status, 200); assert.equal(image.headers.get("content-type"), "image/png"); assert.deepEqual(Buffer.from(await image.arrayBuffer()), PNG);
  assert.equal((await fetch(`${base}/api/inventory/sprite/another_campaign/${knife.id}`)).status, 404);
  assert.equal((await fetch(`${base}/api/inventory/sprite/turn_fixture/${id("NPC lantern")}`)).status, 404);
  assert.equal((await fetch(`${base}/api/inventory/sprite/turn_fixture/${id("Pending ring")}`)).status, 404);
  assert.equal((await fetch(`${base}/api/inventory/sprite/turn_fixture/%2e%2e%2fsecret`)).status, 404);
  assert.equal((await fetch(`${base}/api/session`).then(r => r.json())).inventory.items.length, data.items.length);
  const before = campaign.exportSnapshot(); await repo.saveCampaign(campaign); const loaded = await repo.loadCampaign("turn_fixture");
  const restored = GameSession.fromCampaign({ world, repository: repo, portrait_store: store, createCoordinator: () => ({ async *runTurn() {} }) }, loaded.campaign);
  assert.deepEqual(restored.getPlayerInventoryView(), session.getPlayerInventoryView()); assert.deepEqual(campaign.exportSnapshot(), before); assert.equal(calls, 0);
  apply({ kind: "place_item", item_id: knife.id, position: { kind: "stored", location_id: "test_room" } });
  assert.equal((await fetch(base + knife.sprite_url)).status, 404); assert.ok(!session.getPlayerInventoryView().items.some(i => i.id === knife.id));
  await store.remove("turn_fixture", knife.id, file); apply({ kind: "place_item", item_id: knife.id, position: { kind: "carried", character_id: "nicco" } });
  assert.equal((await fetch(base + knife.sprite_url)).status, 404, "missing file is a placeholder, not gameplay failure");
  assert.equal(calls, 0); assert.equal(CampaignState.restore(world, campaign.exportSnapshot()).exportSnapshot().schema_version, 6);
});
