import test from "node:test";
import assert from "node:assert/strict";
import { household, play } from "./pass10-support.js";

/** Live batch 3 (real narrator, verbatim drafts): door exits that name the place only in a nearby sentence, "footsteps descend" after a comma, and an off-scene character stepping inside. */
const toHall = [{ kind: "runtime_delta", delta: { player_location: "test_hall" } }, { kind: "move_character", character_id: "maren", location_id: "test_hall" }] as const;
const maren = (r: Awaited<ReturnType<typeof play>>) => r.snapshot.runtime.npc_locations.find(n => n.character_id === "maren");

test("live batch 3: a door exit whose nearby wording names the courtyard moves Maren there (five verbatim drafts)", async () => {
  const drafts: readonly string[] = ["Maren looks up from where she sits near the long table. She glances toward the door that leads outside, then back toward Nicco by the hearth.\n\n\"All right,\" she says, rising from the bench. \"I could use some air.\"\n\nShe crosses the hall and pushes through the door into the walled courtyard beyond, leaving Nicco alone with the fire crackling in the hearth and the quiet of the empty table.", "The hearth casts steady warmth across the flagstones. Maren looks up from where she sits near the long table, her expression shifting through something unreadable before settling.\n\nShe doesn't move right away. Her gaze lingers on Nicco for a beat, then she pushes back from the table and stands. \"If you want,\" she says, her tone flat enough that it could be agreement or simply the path of least resistance. She crosses the hall toward the door that opens onto the courtyard, pulls it wide, and steps through into the open air. The door swings partly shut behind her, leaving a slant of grey daylight across the floor.", "Maren glanced toward the courtyard door, then back at Nicco by the hearth. She hesitated, one hand resting on the edge of the long table.\n\n\"I'll be right out there if you need me,\" she said, and crossed the hall. The door opened, letting in a breath of cooler air before she stepped through and pulled it shut behind her.\n\nThe fire crackled softly in the hearth. Nicco stood alone in the hall.", "Nicco stays by the hearth. Maren looks up at him, her expression unreadable for a moment.\n\n\"All right,\" she says, and moves toward the door that leads out to the courtyard. She pulls it open, letting a breath of cooler air into the hall before stepping through. The door falls shut behind her, and the hall is quiet save for the faint crackle of the fire.", "Nicco remained by the hearth, the low fire casting warmth across the stone floor. Maren looked up from where she stood near the long table. She hesitated a moment, then gave a small nod and crossed the hall toward the door that led out to the courtyard. The latch clicked behind her, and the hall settled into quiet, save for the crackle of the fire and the faint draft that curled in under the door."];
  for (const [k, draft] of drafts.entries()) {
    const r = await play(draft, "I stay by the hearth. Maren, go out into the courtyard for some air.", { fixture: household(["maren"], toHall, { courtyard: true }) });
    assert.equal(r.where("maren"), "test_yard", `draft ${k}`);
    assert.equal(r.snapshot.runtime.scene.player_location, "test_hall");
  }
});
test("live batch 3: 'her footsteps descend, growing fainter' after a comma is Maren's descent, never Gerome's", async () => {
  const r = await play("Maren looks up at him. For a moment she doesn't move, her expression shifting through surprise and something harder to read — confusion, maybe the start of hurt — before it settles into a tight, closed look. She pushes back from the table and stands.\n\n\"Fine,\" she says, her voice flat. She crosses the small room to the stairs without looking at Brenna or Gerome, and her footsteps descend, growing fainter until the sound of the lower hall swallows them.\n\nBrenna, still seated, watches the stairway for a beat after Maren has gone. Her grey eyes move to Nicco, but she says nothing. Gerome remains where he stands, inert as the stone he's made of, revealing nothing.", "Maren, leave the room right now. I mean it.", { members: ["maren", "brenna", "gerome"] });
  assert.equal(r.where("maren"), "test_hall");
  assert.equal(r.where("gerome"), "test_room");
  assert.equal(r.where("brenna"), "test_room");
});
test("live batch 3: 'footsteps receding down toward the main hall' after a nod is a recognised descent", async () => {
  const r = await play("Nicco settled against the arched window's frame with his reading, the late-morning light falling across the page. The room was quiet save for the faint creak of the building and the distant sounds filtering up from beyond the walls.\n\nMaren glanced at him, then nodded and crossed to the stairs without protest, her footsteps receding down toward the main hall.\n\nBrenna remained seated, watchful, her grey eyes tracking Maren's departure before settling back toward the middle distance. Gerome stood motionless in his place, a patient shape of shaped stone, saying nothing — as he always said nothing.", "I read by the window. Maren, go down to the main hall, please.", { members: ["maren", "brenna", "gerome"] });
  assert.equal(r.where("maren"), "test_hall");
  assert.equal(r.where("brenna"), "test_room");
});
test("live batch 3: an off-scene Maren who steps inside is back; 'pulls the door shut behind her' is not Brenna leaving", async () => {
  const away = [{ kind: "runtime_delta", delta: { character_movements: [{ character_id: "maren", off_scene: true }] } }] as const;
  const r = await play("The latch clicks and the door swings inward a few inches. Maren stands in the gap, one hand still on the edge of the door. She glances across the small room — at the narrow bed, the table, the arched window letting in grey light — then her gaze settles on the room's other occupants. Brenna sits upright near the wall, watchful but saying nothing, and Gerome's broad stone form occupies the corner like a piece of furniture that happens to breathe.\n\nMaren steps inside and pulls the door shut behind her. She says nothing yet, just looks between the others with the careful, measuring expression of someone trying to read the mood of a room she walked into partway through.", "I look up as the door opens. Who is it?", { members: ["maren", "brenna", "gerome"], extra: away });
  assert.equal(r.where("maren"), "test_room");
  assert.equal(r.where("brenna"), "test_room");
  assert.ok(!maren(r)?.off_scene);
});
test("live batch 3: a mention of the courtyard door with no exit moves nobody", async () => {
  const r = await play("Maren glanced toward the courtyard door, then back at Nicco by the hearth. \"Later,\" she said, and stayed where she was.", "I stay by the hearth. Maren, go out into the courtyard for some air.", { fixture: household(["maren"], toHall, { courtyard: true }) });
  assert.equal(r.where("maren"), "test_hall");
});

test("live batch 4: 'she climbs, her footsteps fading overhead' from the hall is Maren going up to the Observation room", async () => {
  const r = await play("Nicco holds his hands toward the hearth. The fire crackles low, throwing steady warmth across the stone.\n\nMaren glances toward the stairs at the far end of the hall, then back to him. She pushes away from the table where she'd been sitting and crosses to the foot of the steps. Without argument, she climbs, her footsteps fading overhead until a door clicks softly shut.", "I warm my hands at the hearth. Maren, go back upstairs to the Observation room, please.", { fixture: household(["maren"], toHall) });
  assert.equal(r.where("maren"), "test_room");
});
test("live batch 4: 'stepping through into the courtyard beyond. The door settled shut behind her' is a move to the courtyard", async () => {
  const r = await play("Nicco lingered by the hearth, the warmth of the fire pressing against his side. Across the hall, Maren straightened from where she'd been standing near the long table.\n\nShe looked his way, her expression unreadable for a moment. Then she gave a small nod and moved toward the door at the back of the hall without a word, pulling it open and stepping through into the courtyard beyond. The door settled shut behind her, cutting off the cooler draft that had briefly stolen in.\n\nThe hall fell quiet save for the pop and settle of burning wood in the hearth.", "I stay by the hearth. Maren, go out into the courtyard for some air.", { fixture: household(["maren"], toHall, { courtyard: true }) });
  assert.equal(r.where("maren"), "test_yard");
});
test("live batch 4: 'crosses the narrow room to the stairhead, and descends' is Maren going down", async () => {
  const r = await play("Maren's expression shifts. She holds still for a beat, looking at Nicco, then pushes back from the table and stands. She says nothing, crosses the narrow room to the stairhead, and descends. Her footsteps fade below.\n\nGerome remains where it stands, motionless, the stone of its bulk catching the thin light from the arched window. Brenna, seated and alert, watches Maren go, then turns her grey eyes back across the room. Her mouth opens as if she might speak, but she closes it again and settles back against the wall, arms folded loosely over her midsection.", "Maren, leave the room right now. I mean it.", { members: ["maren", "brenna", "gerome"] });
  assert.equal(r.where("maren"), "test_hall");
  assert.equal(r.where("brenna"), "test_room");
});
test("live batch 4: a character who steps inside and lets the door fall shut behind her has arrived; she is not committed OFF_SCENE", async () => {
  const r = await play("The door swings inward, letting a slant of hallway light cut across the narrow bed. Maren stands in the doorway, one hand still on the latch. She pauses there, taking in the room — Brenna seated and alert near the table, Gerome's bulk of fitted stone standing motionless to one side, and Nicco on the bed looking up at her.\n\nShe steps inside, letting the door fall shut behind her with a soft click. \"Didn't mean to interrupt,\" she says, though she doesn't sound apologetic about it. Her gaze moves from Brenna to Gerome and lingers there a moment, the way people tend to look at the construct when they haven't quite gotten used to him. Then she settles against the wall near the arched window, arms folded loosely, watching whatever this is with the quiet patience of someone who lives here and has decided that includes being present for it.", "I look up as the door opens. Who is it?", { members: ["maren", "brenna", "gerome"] });
  assert.equal(r.where("maren"), "test_room");
  assert.ok(!maren(r)?.off_scene);
});
test("live batch 5: 'stepped through into the courtyard, letting the door fall shut behind her' is an exit to the courtyard, not an arrival", async () => {
  const r = await play("Maren glanced toward the door at the suggestion. She nodded and crossed the hall, pulling the door open. Cool air drifted in for a moment before she stepped through into the courtyard, letting the door fall shut behind her.\n\nThe hearth crackled at Nicco's back. The hall was quiet now—just the fire and the faint sounds of evening beyond the walls.", "I stay by the hearth. Maren, go out into the courtyard for some air.", { fixture: household(["maren"], toHall, { courtyard: true }) });
  assert.equal(r.where("maren"), "test_yard");
});
test("live movement: door wording that is not an exit moves nobody (zero new false positives)", async () => {
  for (const t of ["Maren sat down beside the courtyard door and watched the hearth.", "Maren pulled the courtyard door open for a moment, felt the cold, and shut it again, staying where she was.",
    "Maren glanced at the door that leads out to the courtyard. \"Later,\" she said. Her footsteps stayed on the flagstones.", "Maren stepped into the hall from the stairs and let the door fall shut behind her."]) {
    const r = await play(t, "I stay by the hearth. Maren, go out into the courtyard for some air.", { fixture: household(["maren"], toHall, { courtyard: true }) });
    assert.equal(r.where("maren"), "test_hall", t);
  }
});
test("live batch 6: 'The door opens to a draft before closing behind her' is an exit to the courtyard", async () => {
  const r = await play("The hearth crackles steadily, throwing warmth across the flagstones near where Nicco stands. Maren is at the long table, and at his words she looks up. She hesitates a moment, glancing toward the door that leads out to the courtyard, then pushes back from the table and rises.\n\n\"All right,\" she says, and crosses the hall. The door opens to a draft of cooler air before closing behind her.\n\nNicco remains alone by the hearth. The hall is quiet save for the fire and the faint sounds from beyond the door — a gust of wind, the scrape of her boots on stone.", "I stay by the hearth. Maren, go out into the courtyard for some air.", { fixture: household(["maren"], toHall, { courtyard: true }) });
  assert.ok(r.where("maren") === "test_yard" || maren(r)?.off_scene, "she left, so state must say so");
  assert.notEqual(r.where("maren"), "test_hall");
});
test("live batch 6: 'A faint creak marks her passage up the stairs' is Maren going up", async () => {
  const r = await play("The words hang in the hall for a moment. Maren looks up, her expression unreadable, then gives a small nod. She pushes back from the table and crosses toward the far side of the hall, her footsteps steady on the stone floor. She does not ask why or hesitate, nor does she hurry.\n\nA faint creak marks her passage up the stairs, and then the sound of her steps fades into the upper floor. The hall settles into quiet, the hearth crackling softly against the stillness.", "Maren, go upstairs.", { fixture: household(["maren"], toHall) });
  assert.equal(r.where("maren"), "test_room");
});
test("live batch 7: three more verbatim descents and ascents by sound or stair wording are movements, not silent divergences", async () => {
  for (const [draft, input, expected, fixture] of [
    ["Maren looked up, her expression tightening. She opened her mouth as if to say something, then closed it. She pushed back from the table and stood, her chair scraping softly against the floorboards.\n\n\"Fine,\" she said, her voice flat. She crossed the narrow room to the stairs without looking back and descended, her footsteps fading below.\n\nBrenna watched her go, grey eyes tracking the movement. Gerome remained where he stood, motionless, his stone bulk taking up a fair portion of the small room. The arched window let in the ordinary daylight, and the room settled into quiet.", "Maren, leave the room right now. I mean it.", "test_hall", household(["maren", "brenna", "gerome"])],
    ["Maren looked at Nicco. She didn't move right away — her mouth opened slightly, then closed again. Whatever she read in his face or heard in his voice was enough.\n\nShe pushed up from wherever she'd been sitting and walked to the door without a word. Her footsteps were quick on the stairs down, and then the main hall's murmur swallowed them.\n\nBrenna remained seated, grey eyes tracking the exchange but offering no comment. Gerome stood motionless, as stone constructs do.", "Maren, leave the room right now. I mean it.", "test_hall", household(["maren", "brenna", "gerome"])],
    ["Nicco holds his hands toward the hearth. The fire crackles softly against the hall's quiet, casting warm light across the long table.\n\nMaren glances toward the stairs at the far side of the hall, then back at Nicco. She hesitates for a moment, then gives a small nod and crosses to the stairway. Her footsteps recede upward until the hall settles into stillness again, nothing left but the fire and the scrape of a log settling in the grate.", "I warm my hands at the hearth. Maren, go back upstairs to the Observation room, please.", "test_room", household(["maren"], toHall)],
  ] as const) {
    const r = await play(draft, input, { fixture });
    assert.equal(r.where("maren"), expected, draft.slice(-120));
  }
});
test("live batch 8: 'descends the narrow stairs', 'disappeared around the turn of the staircase above' and 'passes through into the open air' are exits with their direction", async () => {
  for (const [draft, input, check, fixture] of [
    ["Maren's expression shifts. She holds his gaze for a beat, then pushes back from the table and stands. Without a word she crosses the small room, her footsteps quick on the wooden boards, and descends the narrow stairs. The door to the stairwell stays open behind her.\n\nBrenna remains seated, grey eyes tracking the exchange. She says nothing. Gerome stands motionless in the corner, a shape of fitted stone, and makes no sound.\n\nThe room is quieter now. From below, faint noise from the main hall drifts up through the open stairwell.", "Maren, leave the room right now. I mean it.", (w: string | undefined) => w === "test_hall", household(["maren", "brenna", "gerome"])],
    ["Maren looked up from where she stood near the long table. She glanced toward the hall's stairway, then back at Nicco, her expression unreadable.\n\n\"All right,\" she said. She moved toward the stairs without further comment, her footsteps quiet against the stone floor, and disappeared around the turn of the staircase above.", "Maren, go upstairs.", (w: string | undefined) => w === "test_room", household(["maren"], toHall)],
    ["Maren glances up from where she stands near the long table. She looks toward the doorway that leads out to the courtyard, then back.\n\n\"All right,\" she says, and crosses the hall. Her footsteps fade as she passes through into the open air beyond.\n\nThe hearth crackles softly. Nicco is alone in the hall.", "I stay by the hearth. Maren, go out into the courtyard for some air.", (w: string | undefined) => w === "test_yard", household(["maren"], toHall, { courtyard: true })],
  ] as const) {
    const r = await play(draft, input, { fixture });
    assert.ok(check(r.where("maren")), `${draft.slice(-100)} -> ${r.where("maren")}`);
  }
});
test("live batch 9: a conjoined 'follows after a moment's pause, pulling the door shut behind her' is never OFF_SCENE when Nicco did not go", async () => {
  const r = await play("Nicco heads for the stairs. Maren straightens up from where she'd been sitting and follows after a moment's pause, pulling the door shut behind her.\n\nGerome remains where he stands, a motionless shape of stone in the quiet room. Brenna watches them go from her seat, saying nothing.", "I set off for the remote docks right now. Maren, come with me.", { members: ["maren", "brenna", "gerome"] });
  assert.equal(r.where("maren"), "test_room");
  assert.ok(!maren(r)?.off_scene);
});
test("live batch 9: 'reaches the landing above' and 'went up without a word, her footsteps faded overhead' are ascents", async () => {
  for (const [draft, input] of [["Maren looks up from where she sits near the long table, her expression unreadable for a moment. She glances toward the stairs, then back at Nicco.\n\n\"Upstairs,\" she repeats, as if weighing the word. She pushes her chair back and stands, brushing her hands against her skirts. \"All right.\"\n\nShe crosses the hall toward the stair, her footsteps light on the stone floor, and climbs without hurrying. The creak of the steps trails off as she reaches the landing above, and the hall settles into the quiet crackle of the hearth.", "Maren, go upstairs."], ["Maren looked at him across the long table, her expression unreadable in the hearthlight. She didn't move right away — just held there for a beat, as if weighing something.\n\nThen she turned toward the far end of the hall where the stairs climbed into shadow, and went up without a word. Her footsteps faded overhead until the hall was quiet again, the fire popping softly in the grate.", "Maren, go upstairs."]] as const) {
    const r = await play(draft, input, { fixture: household(["maren"], toHall) });
    assert.equal(r.where("maren"), "test_room", draft.slice(-100));
  }
});
test("live batch 10: 'Her footsteps were soft going down the stairs' is Maren going down", async () => {
  const r = await play("Maren looked up from where she sat, her expression shifting through something unreadable. She held there a moment, then gave a small nod and rose without argument. Her footsteps were soft going down the stairs, and the door at the bottom opened and closed after a pause.\n\nThe room settled into quiet. Dust motes drifted in the light from the arched window. Brenna remained seated, grey eyes watchful, saying nothing. Gerome stood motionless in his corner, stone limbs locked in patient stillness, as though he had been carved into the room itself.", "I want some quiet. Maren, go out for a while.", { members: ["maren", "brenna", "gerome"] });
  assert.equal(r.where("maren"), "test_hall");
});

/** Live batch 11: wordings the grammar does not resolve to a place. Whatever the state does, the delivered text must never say she left while the state keeps her here. */
test("live batch 11: an exit by sound, stairs or door that commits nothing is withdrawn from the delivered text (no silent divergence)", async () => {
  const cases: readonly (readonly [string, string, string])[] = [["Maren looks up from where she sits. Her expression shifts — a brief tightening around the mouth, something guarded passing behind her eyes. She stands without hurrying, brushes her hands on her skirt, and moves toward the stairs.\n\nGerome remains where he is, a shape of grey stone standing motionless near the wall. Brenna, seated and alert, watches Maren go but says nothing. The door at the bottom of the stairs opens and closes, and then the room is still.", "I want some quiet. Maren, go out for a while.", "destination_less"], ["Brenna glanced up from where she sat, grey eyes moving between Nicco and Maren, but said nothing.\n\nMaren looked at him for a moment, her expression hard to read. Then she nodded, pushed back from the table, and stood. \"All right.\" Her footsteps were soft on the floorboards as she crossed to the door. She pulled it open, slipped through, and let it close behind her with a quiet click. Her steps faded on the stairs.\n\nThe room settled into stillness. Gerome stood motionless in the corner, a shape of pale stone saying nothing, as always. Brenna remained seated, her hands resting in her lap, watching the door Maren had left by. Wind stirred faintly through the arched window.", "I want some quiet. Maren, go out for a while.", "destination_less"], ["Maren blinks, caught mid-breath. Her mouth opens, then closes. She looks at Brenna, at Gerome's impassive stone bulk, then back to Nicco. Whatever she reads in his face is enough. She pushes up from where she sits without another word, skirts past Gerome, and takes the stairs down. Her footsteps fade into the murmur of the hall below.\n\nBrenna watches her go, grey eyes tracking the doorway for a beat after Maren has vanished. She says nothing, but her weight shifts on the narrow bed, and her attention settles on Nicco with the careful quiet of someone choosing not to interrupt.\n\nGerome has not moved.", "Maren, leave the room right now. I mean it.", "order_refused"], ["Maren looked up sharply. For a moment she held still, her lips parting as if to say something, then pressing shut. She pushed back from the table and stood, her chair scraping softly against the floorboards.\n\nShe didn't argue. She crossed the small room without hurrying, passed Gerome's broad stone frame in the doorway, and went down the stairs. Her footsteps faded into the sounds of the hall below.\n\nBrenna remained seated, grey eyes tracking the doorway where Maren had gone. Gerome hadn't moved at all.", "Maren, leave the room right now. I mean it.", "order_refused"], ["Maren glanced up from where she sat near the long table. She looked at Nicco for a moment, then pushed back her chair and stood without argument. Her footsteps crossed the hall floor and she headed for the stairs, climbing them out of view. The hall settled into quiet, the hearth crackling softly against the far wall.", "Maren, go upstairs.", "order_upstairs"]];
  for (const [draft, input, sc] of cases) {
    const stairsUp = sc === "order_upstairs";
    const r = await play(draft, input, { fixture: stairsUp ? household(["maren"], toHall) : household(["maren", "brenna", "gerome"]) });
    const start = stairsUp ? "test_hall" : "test_room", now = maren(r)?.off_scene ? "OFF" : r.where("maren");
    const out = r.result?.narration ?? "";
    if (now === start) assert.doesNotMatch(out, /footsteps? (?:fad|reced)|steps faded|down the stairs|climbing them/i, `${sc}: ${out.slice(0, 200)}`);
  }
});

test("live batch 12: a long-winded 'footsteps … down, down, until the sound fades' and 'the door opens to cool air before closing behind her' are never silent", async () => {
  const cases: readonly (readonly [string, string, string])[] = [["Maren blinks. Her mouth opens, then closes. She looks from Nicco to Brenna, who watches without expression from her seat by the table, then back again. Gerome stands motionless in the corner, a shape of grey stone giving no indication.\n\nFor a moment nobody moves. Then Maren pushes herself up from where she sits, her jaw tight, and crosses the room without a word. Her footsteps are quick on the floorboards and then on the stairs — down, down, until the sound of them fades into the murmur of the hall below.\n\nThe door stays open. Brenna shifts her weight on the narrow bed and lets out a slow breath through her nose, her grey eyes still fixed on the doorway.", "Maren, leave the room right now. I mean it.", "order_refused"], ["Nicco remains by the hearth, the warmth of the fire close against him.\n\nMaren glances toward the door at the back of the hall, then back at him. She pushes off from where she'd been standing near the long table and crosses the room. The door opens to cool air and pale daylight before closing behind her, leaving the hall quiet save for the crackle of the hearth.", "I stay by the hearth. Maren, go out into the courtyard for some air.", "known_courtyard"]];
  for (const [draft, input, sc] of cases) {
    const r = await play(draft, input, { fixture: sc === "known_courtyard" ? household(["maren"], toHall, { courtyard: true }) : household(["maren", "brenna", "gerome"]) });
    const start = sc === "known_courtyard" ? "test_hall" : "test_room", now = maren(r)?.off_scene ? "OFF" : r.where("maren");
    if (now === start) assert.doesNotMatch(r.result?.narration ?? "", /sound of them fades|closing behind her/i, sc);
  }
});
test("live batch 13: 'The door to the courtyard opens, letting in … air before it closes behind her' is an exit to the courtyard", async () => {
  const r = await play("Nicco remains near the hearth, the fire's warmth steady against the hall's cool stone air. Maren glances toward him at the words, her expression hard to read in the flickering light.\n\nShe hesitates for a moment, then gives a small nod and crosses the hall. The door to the courtyard opens, letting in a brief rush of evening air before it closes behind her. The hall settles into quiet, the fire popping softly in the grate.", "I stay by the hearth. Maren, go out into the courtyard for some air.", { fixture: household(["maren"], toHall, { courtyard: true }) });
  assert.ok(r.where("maren") === "test_yard" || maren(r)?.off_scene);
});
