import type { ReflectionRequest, ReflectionProvider } from '../src/turn/reflection.js';
import { ReflectionPacing } from '../src/turn/reflection-pacing.js';
/** Test-only structured provider fixtures; never a production output repair. */
export function instantReflectionPacing() { let now = 0; const sleeps: number[] = []; return { pacing: new ReflectionPacing(() => now, async (ms) => { sleeps.push(ms); now += ms; }), sleeps }; }
export function testTrajectory(request: ReflectionRequest, dimension = 'trust') {
    const es = request.evidence.filter(e => e.evidence_type === 'relationship_change' && e.owner_character_id === request.character.id && e.payload.dimension === dimension).sort((a, b) => a.revision! - b.revision!);
    return { subject_character_id: request.character.id, confidence: 'high', evidence_refs: es.map(e => e.ref), claim: { type: 'relationship_trajectory', target_character_id: es[0]!.payload.other_id, dimension, from: es[0]!.payload.from, to: es.at(-1)!.payload.to, direction: es.every(e => ['none', 'low', 'moderate', 'high'].indexOf(String(e.payload.to)) > ['none', 'low', 'moderate', 'high'].indexOf(String(e.payload.from))) ? 'increase' : 'mixed', transition_count: es.length } };
}
export function testContrast(request: ReflectionRequest) { const es = request.evidence.filter(e => e.evidence_type === 'relationship_change' && e.owner_character_id === request.character.id), dimensions = [...new Set(es.map(e => e.payload.dimension))], a = es.filter(e => e.payload.dimension === dimensions[0]).at(-1)!, b = es.filter(e => e.payload.dimension === dimensions[1]).at(-1)!; return { subject_character_id: request.character.id, confidence: 'high', evidence_refs: es.map(e => e.ref), claim: { type: 'relationship_contrast', target_character_id: a.payload.other_id, dimension_a: dimensions[0], state_a: a.payload.to, dimension_b: dimensions[1], state_b: b.payload.to } }; }
export function testMovement(request: ReflectionRequest) { const es = request.evidence.filter(e => e.evidence_type === 'movement' && e.owner_character_id === request.character.id).sort((a, b) => a.revision! - b.revision!); return { subject_character_id: request.character.id, confidence: 'high', evidence_refs: es.map(e => e.ref), claim: { type: 'movement_trajectory', locations: [es[0]!.payload.from, ...es.map(e => e.payload.to)], transition_count: es.length } }; }
export function testEnvironment(request: ReflectionRequest) { const es = request.evidence.filter(e => e.evidence_type === 'household_context'); return { subject_character_id: request.character.id, confidence: 'high', evidence_refs: es.map(e => e.ref), claim: { type: 'environmental_shared_rule_text', household_id: es[0]!.payload.household_id, relation: 'shared_exact_segment', anchor_ref: es[0]!.ref, segment_index: 1, occurrence_count: es.length } }; }
export const productionStub = (make: (request: ReflectionRequest) => unknown[]): ReflectionProvider => ({ async reflect(request) { return { text: JSON.stringify({ proposals: make(request) }), model: 'qwen/qwen3.8-flash', provider: 'Alibaba' }; } });
