import test from "node:test";
import assert from "node:assert/strict";
import {ProviderError,type ProviderFailureClass} from "../src/llm/errors.js";
import {failureClass,technicalRetryReason,invalidStructured,maintenanceCall,diagnosticCall,ReliabilityMetrics} from "../src/llm/reliability.js";
import {TurnCoordinator} from "../src/turn/turn-coordinator.js";
import {TurnError,type TurnEvent} from "../src/turn/turn-types.js";
import {setup,collect,transfer,metadata,mockNarrator} from "./turn-fixtures.js";
import {fakeRetry,scriptedController,scriptedNarrator} from "./provider-failure-scripts.js";
import {OpenRouterClient} from "../src/llm/openrouter/client.js";
import {MiniMaxNarratorProvider} from "../src/llm/openrouter/minimax-narrator.js";
import {reflectAfterTurn} from "../src/turn/reflection.js";
import {mannerismFixture} from "../src/dev/d10-mannerism-corpus.js";
import {MannerismMaintenance} from "../src/turn/mannerism-extraction.js";
import {OpenRouterStateControllerProvider} from "../src/llm/openrouter/state-controller.js";
import {MannerismPortrayalGate} from "../src/turn/mannerism-portrayal-gate.js";
import type {TurnDiagnostics} from "../src/turn/turn-diagnostics.js";
const input="I give boots to Brenna.",text="Brenna accepts boots from Nicco.";
for(const category of ["malformed_envelope","finish_reason_length","empty_output","schema_invalid","parser_failure"]as const)test(`critical technical ${category}: same request, one retry, one state effect`,async()=>{
 const f=setup(),retry=fakeRetry(),requests:string[]=[];let n=0;
 const controller={async propose(r:Parameters<ReturnType<typeof scriptedController>["propose"]>[0]){requests.push(JSON.stringify(r));if(n++===0)throw new ProviderError("structured_output_invalid",undefined,undefined,category);return{commands:[transfer],...metadata};}};
 const co=new TurnCoordinator(f.world,mockNarrator(text),controller,f.retrieval,{provider_retry:retry.policy,reliability_contract:true}),base=f.campaign.revision;
 const events=await collect(co.runTurn({campaign:f.campaign,player_input:input}));assert.equal(events.at(-1)!.type,"turn_completed");assert.equal(f.campaign.revision,base+1);assert.equal(events.filter(e=>e.type==="state_committed").length,1);assert.equal(requests.length,2);assert.equal(requests[0],requests[1]);assert.equal(f.campaign.exportSnapshot().items.find(i=>i.id==="boots")!.owner_id,"brenna");
});
for(const fault of ["timeout","malformed","length"]as const)test(`narrator ${fault} then success buffers invalid attempt; publishes after commit`,async()=>{
 const f=setup(),base=f.campaign.revision,retry=fakeRetry();let calls=0;const bodies:string[]=[];
 const client=new OpenRouterClient({api_key:()=>"fixture-key",fetch:async(_url,init)=>{bodies.push(String(init?.body));if(calls++===0){if(fault==="timeout")throw new ProviderError("timeout");if(fault==="malformed")return new Response("{bad");return new Response(`data: ${JSON.stringify({choices:[{delta:{content:text},finish_reason:"length"}]})}

data: [DONE]

`);}return new Response(`data: ${JSON.stringify({choices:[{delta:{content:text},finish_reason:"stop"}],usage:{}})}

data: [DONE]

`);}});
 // Non-streaming generation adapted to the same narrator interface avoids fake SSE repairs.
 const real=new MiniMaxNarratorProvider(client),narrator={generate:real.generate.bind(real),async *stream(r:Parameters<typeof real.generate>[0]){try{const result=await real.generate(r);yield{type:"text_delta"as const,text:result.text};yield{type:"completed"as const,result};}catch(error){yield{type:"error"as const,text:"",incomplete:true as const,error:error as ProviderError};}}};
 const co=new TurnCoordinator(f.world,narrator,scriptedController([transfer]),f.retrieval,{provider_retry:retry.policy,reliability_contract:true});const events:TurnEvent[]=[];
 for await(const e of co.runTurn({campaign:f.campaign,player_input:input})){events.push(e);if(e.type==="narration_delta")assert.equal(f.campaign.revision,base+1);}
 assert.equal(events.at(-1)!.type,"turn_completed");assert.equal(calls,2);assert.equal(bodies[0],bodies[1]);assert.equal(events.filter(e=>e.type==="narration_delta").length,1);
});
for(const subsystem of ["narrator","controller"]as const)test(`${subsystem} exhausted: controlled failure, no published draft, no mutation`,async()=>{const f=setup(),before=f.campaign.exportSnapshot(),retry=fakeRetry();const n=scriptedNarrator([text],subsystem==="narrator"?["malformed","malformed"]:["ok"]),c=scriptedController([transfer],subsystem==="controller"?["malformed","malformed"]:["ok"]);const co=new TurnCoordinator(f.world,n,c,f.retrieval,{provider_retry:retry.policy,reliability_contract:true});const events=await collect(co.runTurn({campaign:f.campaign,player_input:input}));assert.equal(events.at(-1)!.type,"turn_failed");assert.equal(f.campaign.exportSnapshot(),before);assert.equal(events.some(e=>e.type==="narration_delta"||e.type==="state_committed"),false);});
test("stale revision during technical retry aborts without a second provider attempt or candidate effects",async()=>{const f=setup(),retry=fakeRetry({},()=>f.campaign.apply({expected_revision:f.campaign.revision,commands:[{kind:"runtime_delta",delta:{time_advance_minutes:1}}]})),c=scriptedController([transfer],["malformed","ok"]);const events=await collect(new TurnCoordinator(f.world,mockNarrator(text),c,f.retrieval,{provider_retry:retry.policy,reliability_contract:true}).runTurn({campaign:f.campaign,player_input:input}));assert.equal(c.calls(),1);assert.equal(events.at(-1)!.type,"turn_failed");assert.equal((events.at(-1)as {code:string}).code,"stale_turn");assert.equal(f.campaign.exportSnapshot().items.find(i=>i.id==="boots")!.owner_id,"nicco");});
test("strict structured parser rejects prose/fences/truncation/unknown fields without repair",()=>{for(const s of ['{"x":1} trailing','```json\n{"x":1}\n```','{"x":1','', '{"x":1,"unknown":2}'])assert.throws(()=>invalidStructured(s,v=>!!v&&typeof v==="object"&&Object.keys(v).length===1&&"x"in v));assert.deepEqual(invalidStructured('{"x":1}',v=>!!v),{x:1});});
test("HTTP 400/auth/refusal and semantic rejection never trigger a technical retry",()=>{for(const e of [new ProviderError("invalid_provider_response",undefined,undefined,"http_nonretryable"),new ProviderError("authentication_error"),new ProviderError("model_refusal"),new Error("semantically rejected")])assert.equal(technicalRetryReason(e),undefined);});
for(const fault of ["malformed","length","provider"]as const)test(`reflection ${fault}: default two technical attempts, no notes, finalized player state unaffected`,async()=>{const f=mannerismFixture();for(const conditions of [["sore"],[],["sore"],[]])f.campaign.apply({expected_revision:f.campaign.revision,commands:[{kind:"set_condition",character_id:"maren",conditions}]});const before=f.campaign.exportSnapshot();let calls=0;const runs=await reflectAfterTurn(f.campaign,f.world,{async reflect(){calls++;if(fault!=="malformed")throw new ProviderError("invalid_provider_response",undefined,undefined,fault==="length"?"finish_reason_length":"invalid_provider_response");return{text:"{bad"};}});assert.ok(runs.length>0);assert.equal(calls,2);assert.equal(f.campaign.exportSnapshot(),before);assert.equal(runs[0]!.attempts!.attempts,2);});
for(const recover of [false,true])test(`extractor malformed ${recover?"then success":"skip"}: no duplicate observation effect`,async()=>{const f=mannerismFixture();let calls=0;const retry=fakeRetry();const m=new MannerismMaintenance(f.world,{async extract(r){calls++;if(calls===1)return{text:"{bad"};const t=r.turns[0]!;return{text:JSON.stringify({owned_reviewed_ids:r.owned.map(o=>o.id),observations:[{turn_sequence:t.sequence,character_id:"brenna",action:"two_finger_tap",trigger:"none",evidence_quote:t.narration,requires_item_id:null,requires_entity_id:null,equivalent_owned_ids:[]}]})};}},recover?retry.policy:undefined);
 let result;for(let i=0;i<4;i++)result=await m.afterFinalizedTurn(f.campaign,`contract_${i}`,{narration:i===0?"Brenna drums two fingertips.":"The room is quiet.",final_revision:f.campaign.revision});assert.equal(calls,recover?2:1);assert.equal(result!.status,recover?"processed":"malformed");assert.equal(result!.metrics.observations_considered,recover?1:0);assert.ok(f.campaign.exportSnapshot().mannerism_learning!.candidates.every(c=>c.evidence.length<=1));});
test("D26 diagnostic failure logs once, skips and cannot block or commit",async()=>{let logged:ProviderFailureClass[]=[];assert.equal(await diagnosticCall(async()=>{throw new ProviderError("timeout");},c=>logged.push(c)),undefined);assert.deepEqual(logged,["timeout"]);assert.equal(await diagnosticCall(async()=>{throw Error();},()=>{throw Error();}),undefined);});
test("maintenance optional retry respects revision and exposes normalized technical counters",async()=>{let n=0;const metrics=new ReliabilityMetrics(),retry=fakeRetry();const value=await maintenanceCall({subsystem:"reflection",policy:retry.policy,checkpoint:()=>{},metrics,run:async()=>{if(n++===0)throw new ProviderError("invalid_provider_response",undefined,undefined,"finish_reason_length");return 7;}});assert.equal(value,7);assert.equal(metrics.counters.maintenance_provider_calls,2);assert.equal(metrics.counters.maintenance_retries,1);assert.equal(metrics.counters.finish_reason_length_count,1);assert.equal(failureClass(new TurnError("stale_turn")),"stale_revision");});
for(const fault of ["malformed","timeout","length","wrong_schema"]as const)test(`actual strict controller ${fault} then success: unmodified envelope, one commit`,async()=>{const f=setup(),bodies:string[]=[];let calls=0;const valid=JSON.stringify({commands:[{command:transfer,evidence_quote:text}]});const client=new OpenRouterClient({api_key:()=>"fixture-key",fetch:async(_url,init)=>{bodies.push(String(init?.body));const first=calls++===0;if(first&&fault==="timeout")throw new ProviderError("timeout");const content=first&&fault==="malformed"?"{bad":first&&fault==="wrong_schema"?JSON.stringify({commands:[{...transfer,evidence:text}]}):valid;return Response.json({choices:[{message:{content},finish_reason:first&&fault==="length"?"length":"stop"}],usage:{}});}});const controller=new OpenRouterStateControllerProvider(client,{strict_output:true});const co=new TurnCoordinator(f.world,mockNarrator(text),controller,f.retrieval,{provider_retry:fakeRetry().policy,reliability_contract:true});const events=await collect(co.runTurn({campaign:f.campaign,player_input:input}));assert.equal(events.at(-1)!.type,"turn_completed");assert.equal(calls,2);assert.equal(bodies[0],bodies[1]);assert.equal(events.filter(e=>e.type==="state_committed").length,1);});
for(const exhausted of [false,true])test(`reconciliation technical malformed ${exhausted?"exhausted aborts":"retry recovers"} before commit`,async()=>{const f=setup(),before=f.campaign.exportSnapshot(),n=scriptedNarrator([text,"Brenna looks at the boots and hesitates."],exhausted?["ok","malformed","malformed"]:["ok","malformed","ok"]),controller=scriptedController([]);const events=await collect(new TurnCoordinator(f.world,n,controller,f.retrieval,{provider_retry:fakeRetry().policy,reliability_contract:true}).runTurn({campaign:f.campaign,player_input:input}));assert.equal(n.calls(),3);assert.equal(events.at(-1)!.type,exhausted?"turn_failed":"turn_completed");if(exhausted){assert.equal(f.campaign.exportSnapshot(),before);assert.equal(events.some(e=>e.type==="narration_delta"),false);}else assert.equal(events.filter(e=>e.type==="state_committed").length,1);});
test("candidate contract prevents concurrent duplicate effects and leaves pre-deliverable abandonment uncommitted",async()=>{const f=setup(),before=f.campaign.exportSnapshot(),controller=scriptedController([transfer]);const co=new TurnCoordinator(f.world,mockNarrator(text),controller,f.retrieval,{provider_retry:fakeRetry().policy,reliability_contract:true});const stream=co.runTurn({campaign:f.campaign,player_input:input});assert.equal((await stream.next()).value!.type,"turn_started");const duplicate=await collect(co.runTurn({campaign:f.campaign,player_input:input}));assert.equal((duplicate.at(-1)as {code:string}).code,"turn_in_progress");await stream.return(undefined);assert.equal(f.campaign.exportSnapshot(),before);assert.equal(controller.calls(),0);});
test("actual D26 observer exception cannot block a valid turn or alter its effects",async()=>{const original=MannerismPortrayalGate.prototype.inspect,f=setup(),records:TurnDiagnostics[]=[];MannerismPortrayalGate.prototype.inspect=()=>{throw Error("Injected diagnostic failure");};try{const events=await collect(new TurnCoordinator(f.world,mockNarrator(text),scriptedController([transfer]),f.retrieval,{reliability_contract:true,provider_retry:fakeRetry().policy,diagnostics_sink:r=>records.push(structuredClone(r)as TurnDiagnostics)}).runTurn({campaign:f.campaign,player_input:input}));assert.equal(events.at(-1)!.type,"turn_completed");assert.equal(records[0]!.provider_reliability!.shadow_skips,1);assert.equal(events.filter(e=>e.type==="state_committed").length,1);}finally{MannerismPortrayalGate.prototype.inspect=original;}});
test("candidate coordinator refuses legacy normalized controller authority, with bounded retries and no mutation",async()=>{const f=setup(),before=f.campaign.exportSnapshot();let calls=0;const controller=new OpenRouterStateControllerProvider(new OpenRouterClient({api_key:()=>"fixture-key",fetch:async()=>{calls++;return Response.json({choices:[{message:{content:JSON.stringify({commands:[{...transfer,evidence:text}]})},finish_reason:"stop"}],usage:{}});}}));const events=await collect(new TurnCoordinator(f.world,mockNarrator(text),controller,f.retrieval,{reliability_contract:true,provider_retry:fakeRetry().policy}).runTurn({campaign:f.campaign,player_input:input}));assert.equal(events.at(-1)!.type,"turn_failed");assert.equal(calls,2);assert.equal(f.campaign.exportSnapshot(),before);assert.equal(events.some(e=>e.type==="narration_delta"),false);});
