import test from 'node:test';
import assert from 'node:assert/strict';
import type {StructuredEvidence} from '../src/dev/reflection-v2.js';
import {validateStructuredClaimV22} from '../src/dev/reflection-v22.js';
import {validateStructuredClaimV23} from '../src/dev/reflection-v23.js';
function fixture(){
 const entry=(ref:string,type:string,revision:number,payload:Record<string,unknown>):StructuredEvidence=>({ref,evidence_version:2,evidence_type:type as StructuredEvidence['evidence_type'],subject_character_id:'maren',owner_character_id:'maren',revision,world_minute:revision,event_id:ref,payload});
 const a=entry('trust-history','relationship_change',2,{actor_id:'maren',other_id:'brenna',dimension:'trust',from:'low',to:'moderate'}),b=entry('wariness-history','relationship_change',3,{actor_id:'maren',other_id:'brenna',dimension:'wariness',from:'moderate',to:'high'}),snapshot=entry('current','relationship_snapshot',4,{target_character_id:'brenna',dimensions:{trust:'moderate',wariness:'high'}});
 const proposal={subject_character_id:'maren',confidence:'high',evidence_refs:[a.ref,b.ref],claim:{type:'relationship_contrast',target_character_id:'brenna',dimension_a:'trust',state_a:'moderate',dimension_b:'wariness',state_b:'high'}};
 return {a,b,snapshot,proposal,catalog:[a,b,snapshot],check:(p:unknown=proposal,c:readonly StructuredEvidence[]=[a,b,snapshot])=>validateStructuredClaimV23(p,c,'maren')};
}
test('V23 current contrast verifies uncited authoritative state with both-dimension provenance',()=>{const f=fixture();assert.equal(validateStructuredClaimV22(f.proposal,f.catalog,'maren').accepted,false);const d=f.check();assert.equal(d.accepted,true);assert.equal(d.authority_ref,'current');assert.deepEqual(d.proposal,f.proposal);assert.equal(f.check({...f.proposal,evidence_refs:['current']}).accepted,true);});
test('V23 rejects missing, mismatched, absent and ambiguous current authority',()=>{const f=fixture();assert.equal(f.check(f.proposal,[f.a,f.b]).accepted,false);for(const dimensions of [{trust:'low',wariness:'high'},{trust:'moderate'}])assert.equal(f.check(f.proposal,[f.a,f.b,{...f.snapshot,payload:{...f.snapshot.payload,dimensions}}]).accepted,false);assert.equal(f.check(f.proposal,[...f.catalog,{...f.snapshot,ref:'ambiguous'}]).accepted,false);assert.equal(f.check(f.proposal,[f.a,f.b,{...f.snapshot,owner_character_id:'brenna'}]).accepted,false);});
test('V23 rejects stale snapshot and post-snapshot events without turning history into current truth',()=>{const f=fixture(),stale={...f.snapshot,ref:'stale',revision:1};assert.equal(f.check({...f.proposal,evidence_refs:['stale']},[...f.catalog,stale]).accepted,false);assert.equal(f.check(f.proposal,[...f.catalog,{...f.a,ref:'later',revision:5}]).accepted,false);});
test('V23 current truth cannot authorize unrelated, partial, foreign or unknown citations',()=>{const f=fixture(),move={...f.a,ref:'move',evidence_type:'movement' as const,payload:{from:'room',to:'hall'}};assert.equal(f.check({...f.proposal,evidence_refs:['move']},[...f.catalog,move]).accepted,false);assert.equal(f.check({...f.proposal,evidence_refs:['trust-history']}).accepted,false);assert.equal(f.check({...f.proposal,evidence_refs:['missing']}).accepted,false);assert.equal(f.check({...f.proposal,subject_character_id:'brenna'}).accepted,false);assert.equal(f.check(f.proposal,[...f.catalog,{...f.a}]).accepted,false);});
test('V23 non-contrast claims retain identical V22 proof requirements',()=>{const f=fixture(),p={...f.proposal,claim:{type:'relationship_trajectory',target_character_id:'brenna',dimension:'trust',from:'none',to:'moderate',direction:'increase',transition_count:2}};assert.deepEqual(f.check(p),validateStructuredClaimV22(p,f.catalog,'maren'));assert.equal(f.check(p).accepted,false);});
